"""Initial migration

Revision ID: a7ab56fb56ab
Revises: 
Create Date: 2026-01-06 23:11:15.551599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ab56fb56ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('railways',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name_ja', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('operator_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_railways_id'), 'railways', ['id'], unique=False)
    op.create_index(op.f('ix_railways_name_ja'), 'railways', ['name_ja'], unique=False)
    op.create_index(op.f('ix_railways_operator_id'), 'railways', ['operator_id'], unique=False)
    op.create_table('route_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_station_id', sa.String(), nullable=True),
    sa.Column('to_station_id', sa.String(), nullable=True),
    sa.Column('time_minutes', sa.Float(), nullable=True),
    sa.Column('railway_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_edges_from_station_id'), 'route_edges', ['from_station_id'], unique=False)
    op.create_index(op.f('ix_route_edges_id'), 'route_edges', ['id'], unique=False)
    op.create_index(op.f('ix_route_edges_railway_id'), 'route_edges', ['railway_id'], unique=False)
    op.create_index(op.f('ix_route_edges_to_station_id'), 'route_edges', ['to_station_id'], unique=False)
    op.create_table('station_departures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(), nullable=True),
    sa.Column('station_name', sa.String(), nullable=True),
    sa.Column('railway_id', sa.String(), nullable=True),
    sa.Column('railway_name', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('departure_time', sa.String(), nullable=True),
    sa.Column('train_type', sa.String(), nullable=True),
    sa.Column('destination_station', sa.String(), nullable=True),
    sa.Column('train_number', sa.String(), nullable=True),
    sa.Column('weekday_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_departures_departure_time'), 'station_departures', ['departure_time'], unique=False)
    op.create_index(op.f('ix_station_departures_id'), 'station_departures', ['id'], unique=False)
    op.create_index(op.f('ix_station_departures_railway_id'), 'station_departures', ['railway_id'], unique=False)
    op.create_index(op.f('ix_station_departures_railway_name'), 'station_departures', ['railway_name'], unique=False)
    op.create_index(op.f('ix_station_departures_station_id'), 'station_departures', ['station_id'], unique=False)
    op.create_index(op.f('ix_station_departures_station_name'), 'station_departures', ['station_name'], unique=False)
    op.create_index(op.f('ix_station_departures_weekday_type'), 'station_departures', ['weekday_type'], unique=False)
    op.create_table('station_intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_station', sa.String(), nullable=True),
    sa.Column('to_station', sa.String(), nullable=True),
    sa.Column('railway_name', sa.String(), nullable=True),
    sa.Column('time_minutes', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_intervals_from_station'), 'station_intervals', ['from_station'], unique=False)
    op.create_index(op.f('ix_station_intervals_id'), 'station_intervals', ['id'], unique=False)
    op.create_index(op.f('ix_station_intervals_railway_name'), 'station_intervals', ['railway_name'], unique=False)
    op.create_index(op.f('ix_station_intervals_to_station'), 'station_intervals', ['to_station'], unique=False)
    op.create_table('station_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('railway_id', sa.String(), nullable=True),
    sa.Column('railway_name', sa.String(), nullable=True),
    sa.Column('station_id', sa.String(), nullable=True),
    sa.Column('station_name', sa.String(), nullable=True),
    sa.Column('station_index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_orders_id'), 'station_orders', ['id'], unique=False)
    op.create_index(op.f('ix_station_orders_railway_id'), 'station_orders', ['railway_id'], unique=False)
    op.create_index(op.f('ix_station_orders_railway_name'), 'station_orders', ['railway_name'], unique=False)
    op.create_index(op.f('ix_station_orders_station_id'), 'station_orders', ['station_id'], unique=False)
    op.create_index(op.f('ix_station_orders_station_name'), 'station_orders', ['station_name'], unique=False)
    op.create_table('stations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name_ja', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('railway_id', sa.String(), nullable=True),
    sa.Column('station_code', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_id'), 'stations', ['id'], unique=False)
    op.create_index(op.f('ix_stations_name_ja'), 'stations', ['name_ja'], unique=False)
    op.create_index(op.f('ix_stations_railway_id'), 'stations', ['railway_id'], unique=False)
    op.create_table('train_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('railway_id', sa.String(), nullable=True),
    sa.Column('railway_name', sa.String(), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('status_text', sa.String(), nullable=True),
    sa.Column('is_delayed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_statuses_id'), 'train_statuses', ['id'], unique=False)
    op.create_index(op.f('ix_train_statuses_is_delayed'), 'train_statuses', ['is_delayed'], unique=False)
    op.create_index(op.f('ix_train_statuses_railway_id'), 'train_statuses', ['railway_id'], unique=False)
    op.create_index(op.f('ix_train_statuses_railway_name'), 'train_statuses', ['railway_name'], unique=False)
    op.create_index(op.f('ix_train_statuses_timestamp'), 'train_statuses', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_train_statuses_timestamp'), table_name='train_statuses')
    op.drop_index(op.f('ix_train_statuses_railway_name'), table_name='train_statuses')
    op.drop_index(op.f('ix_train_statuses_railway_id'), table_name='train_statuses')
    op.drop_index(op.f('ix_train_statuses_is_delayed'), table_name='train_statuses')
    op.drop_index(op.f('ix_train_statuses_id'), table_name='train_statuses')
    op.drop_table('train_statuses')
    op.drop_index(op.f('ix_stations_railway_id'), table_name='stations')
    op.drop_index(op.f('ix_stations_name_ja'), table_name='stations')
    op.drop_index(op.f('ix_stations_id'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_station_orders_station_name'), table_name='station_orders')
    op.drop_index(op.f('ix_station_orders_station_id'), table_name='station_orders')
    op.drop_index(op.f('ix_station_orders_railway_name'), table_name='station_orders')
    op.drop_index(op.f('ix_station_orders_railway_id'), table_name='station_orders')
    op.drop_index(op.f('ix_station_orders_id'), table_name='station_orders')
    op.drop_table('station_orders')
    op.drop_index(op.f('ix_station_intervals_to_station'), table_name='station_intervals')
    op.drop_index(op.f('ix_station_intervals_railway_name'), table_name='station_intervals')
    op.drop_index(op.f('ix_station_intervals_id'), table_name='station_intervals')
    op.drop_index(op.f('ix_station_intervals_from_station'), table_name='station_intervals')
    op.drop_table('station_intervals')
    op.drop_index(op.f('ix_station_departures_weekday_type'), table_name='station_departures')
    op.drop_index(op.f('ix_station_departures_station_name'), table_name='station_departures')
    op.drop_index(op.f('ix_station_departures_station_id'), table_name='station_departures')
    op.drop_index(op.f('ix_station_departures_railway_name'), table_name='station_departures')
    op.drop_index(op.f('ix_station_departures_railway_id'), table_name='station_departures')
    op.drop_index(op.f('ix_station_departures_id'), table_name='station_departures')
    op.drop_index(op.f('ix_station_departures_departure_time'), table_name='station_departures')
    op.drop_table('station_departures')
    op.drop_index(op.f('ix_route_edges_to_station_id'), table_name='route_edges')
    op.drop_index(op.f('ix_route_edges_railway_id'), table_name='route_edges')
    op.drop_index(op.f('ix_route_edges_id'), table_name='route_edges')
    op.drop_index(op.f('ix_route_edges_from_station_id'), table_name='route_edges')
    op.drop_table('route_edges')
    op.drop_index(op.f('ix_railways_operator_id'), table_name='railways')
    op.drop_index(op.f('ix_railways_name_ja'), table_name='railways')
    op.drop_index(op.f('ix_railways_id'), table_name='railways')
    op.drop_table('railways')
    # ### end Alembic commands ###
